Open API
GoogleCloudPlatform/endpoints-framework-gradle-plugin pull request #36
Opened 2017-04-17 11:16 UTC by xinoxapps

Added support for the OpenAPI action at the server side.

2017-04-17 11:21 UTC, xinoxapps commented
I signed it!

2017-04-17 14:12 UTC, loosebazooka commented
Thanks @xinoxapps I'm not sure if we intended this plugin to cover the open-api generation. However, I'll take a look and see if we can expand the scope of this plugin.

2017-04-17 17:05 UTC, patflynn commented
@xinoxapps and thank you for the PR! We appreciate it.

2017-04-17 17:52 UTC, duchuyctlk commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/task/GenerateOpenApiDocsTask.java
> +}
Please add a new line at end of file 😄

2017-04-17 20:12 UTC, loosebazooka commented
@xinoxapps Can you explain how you intend to use this? We don't really want to include the open-api related features in here. There is generic open-api tooling for gradle that makes sense to use. This is merely a way to bring our previous endpoints functionality up to date, however I believe a compelling use case might sway us.

2017-04-18 09:39 UTC, xinoxapps commented
Hi,

Thank you for your positive feedback. We are also in the progress of migrating our existing projects to the new endpoints framework. 

We are currently missing a convenient way to generate openapi docs for the Google Console Dashboard. Which applies to the following command:

`gcloud service-management deploy openapi.json`

In the Google Docs, there is a [section](https://cloud.google.com/endpoints/docs/frameworks/java/about-cloud-endpoints-frameworks) under tooling about endpoints.cmd. I think this plugin fulfills the role as convenient gradle wrapper. 

> The endpoints command line tool (for Linux), or endpoints.cmd (for Windows) that you can use to generate client libraries, discovery documents, and OpenApi specification configuration file required for Cloud Endpoints

Another compelling use case is to support the following [typescript client library](https://www.npmjs.com/package/openapi-client)

Kind regards, Wendel

2017-04-18 19:38 UTC, loosebazooka requested changes

2017-04-18 19:38 UTC, loosebazooka commented on build.gradle
> +version = '1.0.1-SNAPSHOT'
Please change this back to 1.0.0

2017-04-18 19:38 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/client/EndpointsClientPlugin.java
> +
Undo all these newlines.

2017-04-18 19:38 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/client/EndpointsClientExtension.java
> +  private final File genOpenApiDocsDir;
It does not appear likely that we need to modify the client plugin. The client plugin is designed for generating client libraries for client consumers of endpoints v1.1.

For OpenApi specs, I believe you're going to delegate to another tool. Are you using something to do that? And how are you using it?

2017-04-18 19:38 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/task/GenerateOpenApiDocsTask.java
> + *  Copyright (c) 2016 Google Inc. All Right Reserved.
2017

2017-04-18 19:38 UTC, loosebazooka commented on src/test/java/com/google/cloud/tools/gradle/endpoints/framework/ProjectTests.java
> +
Looks like you reformatted this with 4 spaces? Undo that.

2017-04-18 19:38 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/EndpointsServerPlugin.java
> +            new Action<GenerateOpenApiDocsTask>() {
spacing again, use +4 for line continuations.

2017-04-18 19:38 UTC, loosebazooka commented
@xinoxapps okay, looks like we're going to try and merge this in. Please update based on the review, and thanks again for the contribution.

2017-04-20 20:27 UTC, xinoxapps commented
Requested changes applied

2017-04-26 17:34 UTC, loosebazooka requested changes

2017-04-26 17:34 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/task/GenerateDiscoveryDocsTask.java
> +
Can you remove the changes you made to this file?

2017-04-26 17:34 UTC, loosebazooka commented on src/test/resources/projects/client/src/endpoints/testApi-v1-rest.openapi
> +{
I think we can remove this file.

2017-04-26 17:34 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/EndpointsServerPlugin.java
> +      new Action<GenerateClientLibsTask>() {
please undo the spacing changes here, they were correct before (offset by 2x for line continuation)

2017-04-26 17:34 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/EndpointsServerPlugin.java
> +      new Action<GenerateDiscoveryDocsTask>() {
please undo the spacing changes here, they were correct before (offset by 2x for line continuation)

2017-04-26 17:34 UTC, loosebazooka commented on src/main/java/com/google/cloud/tools/gradle/endpoints/framework/server/EndpointsServerPlugin.java
> +      new Action<GenerateOpenApiDocsTask>() {
I think you need to correct the spacing here +2 spaces from 112 to 133?

2017-04-26 17:34 UTC, loosebazooka commented on README.md
> +* `endpointsOpenApiDocs` - generate openapi documents
Docs will not change until a release. I'll make this update when we do the release.

2017-04-26 19:33 UTC, loosebazooka commented
The plugin now has checkstlye and google-java-format built in.

You should be able to run `./gradlew googleJavaFormat` to auto format most files.

2017-04-27 10:33 UTC, xinoxapps commented
I did a merge with the style branch but ended with several conflicts.

gradle googleJavaFormat has been applied to the srces.

2017-04-28 16:50 UTC, loosebazooka commented
@xinoxapps I cleaned up and added to this PR, in #40 , but it needs your approval, since it contains a commit from you.

2017-05-04 18:24 UTC, closed without merging